const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');

(async () => {
  const browser = await chromium.launch({ ...(process.env.NAPS_CHROME_PATH ? { executablePath: process.env.NAPS_CHROME_PATH } : { channel: 'chrome' }), headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.NAPS_TEST_URL || 'http://127.0.0.1:3000/', { waitUntil: 'networkidle' });
  assert.equal(await page.locator('#naps_grid path').count(), 2, 'enabled grid is drawn as major and minor square lines');
  assert.equal(await page.locator('#naps_grid circle').count(), 0, 'grid is not a dot pattern');
  const canvas = page.locator('.schematic-editor div.relative.overflow-hidden.bg-white').last();
  const rect = await canvas.boundingBox();
  const quick = page.getByRole('button', { name: 'Резистор' }).first();
  const box = await quick.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.wheel(0, 100);
  await page.mouse.move(rect.x + 320, rect.y + 220, { steps: 6 });
  await page.mouse.up();
  const namesAfterDrag = await page.locator('#schematic-world text').allTextContents();
  console.log('palette drag', namesAfterDrag);
  assert.ok(namesAfterDrag.some(name => name.startsWith('C1')), 'wheel changes dragged resistor to capacitor');
  const combo = page.getByRole('combobox', { name: 'Двухполюсники: выбрать элемент' });
  await combo.selectOption({ label: 'Индуктивность' });
  await page.mouse.click(rect.x + 560, rect.y + 220);
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 2);
  console.log('placed transforms', await page.locator('#schematic-world > g[transform^="translate"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('transform'))));
  const componentPoint = { x: rect.x + 320, y: rect.y + 220 };
  await page.mouse.click(componentPoint.x, componentPoint.y, { button: 'right' });
  await page.screenshot({ path: '.work/browser-context.png' });
  const menu = page.getByRole('menu');
  assert.equal(await menu.getByRole('menuitem').count(), 13);
  await menu.getByRole('menuitem', { name: 'Копировать' }).click();
  await page.mouse.click(componentPoint.x, componentPoint.y, { button: 'right' });
  await page.getByRole('menuitem', { name: 'Вставить копию рядом' }).click();
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 3);
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 2);
  await page.keyboard.press('Control+y');
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 3);
  const componentPointAfterRedo = await page.evaluate(() => {
    const group = document.querySelector('#schematic-world > g[transform^="translate(280, 200)"]');
    const svg = group.ownerSVGElement;
    const p = svg.createSVGPoint(); p.x = 0; p.y = 0;
    const result = p.matrixTransform(group.getScreenCTM());
    return { x: result.x, y: result.y };
  });
  await page.mouse.dblclick(componentPointAfterRedo.x, componentPointAfterRedo.y);
  console.log('after double', await page.getByRole('dialog').count(), (await page.locator('body').innerText()).slice(-450));
  await page.screenshot({ path: '.work/browser-double.png' });
  assert.ok(await page.getByRole('dialog').count(), 'double-click opens element properties');
  await page.getByRole('button', { name: 'Отмена' }).click();
  const beforeZoom = await page.locator('#schematic-world').getAttribute('transform');
  await page.getByTitle('Увеличить масштаб').first().click();
  const afterZoom = await page.locator('#schematic-world').getAttribute('transform');
  assert.notEqual(afterZoom, beforeZoom);
  const [png] = await Promise.all([page.waitForEvent('download'), page.getByTitle('Скачать схему как PNG без сетки и служебных отметок').click()]);
  assert.ok(png.suggestedFilename().endsWith('.png'));
  const pngBytes = await fs.readFile(await png.path());
  assert.ok(pngBytes.length > 1000 && pngBytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])), 'exported PNG is a nonempty image');
  const angleBefore = await page.locator('#schematic-world > g[transform^="translate(280, 200)"] > g[transform^="rotate"]').getAttribute('transform');
  const labelsBefore = await page.locator('#schematic-world > g[transform^="translate(280, 200)"] > g[data-element-labels] text').evaluateAll(nodes => nodes.map(node => ({ kind: node.getAttribute('data-label-kind'), x: node.getAttribute('x'), y: node.getAttribute('y'), transform: node.getAttribute('transform') })));
  await page.getByTitle('Повернуть выбранный элемент (R)').click();
  const angleAfter = await page.locator('#schematic-world > g[transform^="translate(280, 200)"] > g[transform^="rotate"]').getAttribute('transform');
  assert.notEqual(angleAfter, angleBefore, '90-degree toolbar rotation changes the component orientation');
  const labelsAfter = await page.locator('#schematic-world > g[transform^="translate(280, 200)"] > g[data-element-labels] text').evaluateAll(nodes => nodes.map(node => ({ kind: node.getAttribute('data-label-kind'), x: node.getAttribute('x'), y: node.getAttribute('y'), transform: node.getAttribute('transform') })));
  assert.notDeepEqual(labelsAfter.map(label => [label.x, label.y]), labelsBefore.map(label => [label.x, label.y]), 'labels change position after component rotation');
  assert.ok(labelsAfter.every(label => !label.transform), 'labels remain upright after component rotation');
  const beforePan = await page.locator('#schematic-world').getAttribute('transform');
  await page.mouse.move(rect.x + 1000, rect.y + 430);
  await page.keyboard.down('Shift');
  await page.mouse.down();
  await page.mouse.move(rect.x + 1050, rect.y + 460, { steps: 5 });
  await page.mouse.up();
  await page.keyboard.up('Shift');
  const afterPan = await page.locator('#schematic-world').getAttribute('transform');
  assert.notEqual(afterPan, beforePan, 'canvas pan updates the world transform');
  const gridTransform = await page.locator('#naps_grid').getAttribute('patternTransform');
  assert.equal(gridTransform, afterPan.replace(/ scale\(.*$/, ''), 'visible grid follows the same pan as schematic world');
  await page.screenshot({ path: '.work/browser-grid-panned.png' });
  await page.getByRole('button', { name: 'Клавиши' }).click();
  const shortcutsDialog = page.getByRole('dialog', { name: 'Горячие клавиши' });
  const selectableCount = await page.evaluate(async () => {
    const { COMPONENT_CATALOG, terminalGroupForType } = await import('/src/components/ComponentPalette.tsx');
    return COMPONENT_CATALOG.filter(item => terminalGroupForType(item.type)).length + 1;
  });
  assert.equal(await shortcutsDialog.locator('button[aria-label^="Назначить:"]').count(), selectableCount + 2, 'keyboard settings include every component and editor action');
  const resistorShortcut = shortcutsDialog.getByRole('button', { name: 'Назначить: Резистор (R)' });
  await resistorShortcut.click();
  await page.keyboard.press('Control+Alt+k');
  assert.match(await resistorShortcut.innerText(), /Ctrl \+ Alt \+ K/, 'modifier combination is captured and displayed');
  const capacitorShortcut = shortcutsDialog.getByRole('button', { name: 'Назначить: Конденсатор (C)' });
  await capacitorShortcut.click();
  await page.keyboard.press('Control+Alt+k');
  assert.match(await shortcutsDialog.getByRole('status').innerText(), /Уже назначено/, 'duplicate binding is rejected with an explanation');
  await page.keyboard.press('Escape');
  await shortcutsDialog.getByRole('button', { name: 'Закрыть' }).click();
  const beforeHotkeyAdd = await page.locator('#schematic-world > g[transform^="translate"]').count();
  await page.keyboard.press('Control+Alt+k');
  await page.mouse.click(rect.x + 820, rect.y + 320);
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), beforeHotkeyAdd + 1, 'custom component shortcut enters placement mode and inserts the component');
  await page.getByRole('button', { name: 'Клавиши' }).click();
  assert.match(await page.getByRole('dialog', { name: 'Горячие клавиши' }).getByRole('button', { name: 'Назначить: Резистор (R)' }).innerText(), /Ctrl \+ Alt \+ K/, 'custom binding persists while the editor remains open');
  await page.getByRole('dialog', { name: 'Горячие клавиши' }).getByRole('button', { name: 'Закрыть' }).click();
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Клавиши' }).click();
  assert.match(await page.getByRole('dialog', { name: 'Горячие клавиши' }).getByRole('button', { name: 'Назначить: Резистор (R)' }).innerText(), /Ctrl \+ Alt \+ K/, 'custom binding persists after reloading the application');
  await page.getByRole('dialog', { name: 'Горячие клавиши' }).getByRole('button', { name: 'Закрыть' }).click();
  console.log(JSON.stringify({ stage: 'ui', beforeZoom, afterZoom, png: png.suggestedFilename(), errors }, null, 2));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
