const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');

(async () => {
  const browser = await chromium.launch({
    ...(process.env.NAPS_CHROME_PATH ? { executablePath: process.env.NAPS_CHROME_PATH } : { channel: 'chrome' }),
    headless: true,
    args: ['--no-sandbox'],
  });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.NAPS_TEST_URL || 'http://127.0.0.1:3000/', { waitUntil: 'networkidle' });
  const canvas = page.locator('.schematic-editor div.relative.overflow-hidden.bg-white').last();
  const rect = await canvas.boundingBox();
  assert(rect && rect.width > 800 && rect.height > 300);
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 0);
  assert.equal(await page.locator('rect[fill="url(#naps_grid)"]').count(), 1);
  await page.getByRole('button', { name: 'Сетка', exact: true }).click();
  assert.equal(await page.locator('rect[fill="url(#naps_grid)"]').count(), 0);
  await page.getByRole('button', { name: 'Сетка', exact: true }).click();
  assert.equal(await page.locator('rect[fill="url(#naps_grid)"]').count(), 1);
  await page.getByRole('button', { name: 'Резистор' }).first().click();
  await page.mouse.click(rect.x + 260, rect.y + 170);
  await page.getByRole('button', { name: 'Резистор' }).first().click();
  await page.mouse.click(rect.x + 560, rect.y + 270);
  const componentTransforms = await page.locator('#schematic-world > g[transform^="translate"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('transform')));
  console.log(JSON.stringify({ stage: 'placed', componentTransforms, gridVisible: await page.locator('rect[fill="url(#naps_grid)"]').count(), errors }, null, 2));
  assert.equal(componentTransforms.length, 2);
  await page.screenshot({ path: '.work/browser-initial.png' });
  const at = (x, y) => ({ x: rect.x + 40 + x, y: rect.y + 30 + y });
  const clickAt = async (x, y) => { const p = at(x, y); await page.mouse.click(p.x, p.y); };
  await clickAt(250, 140);
  assert.equal(await page.locator('#schematic-world path[stroke="transparent"]').count(), 0, 'source click only starts a preview');
  assert.equal(await page.locator('#schematic-world path[stroke-dasharray="4 3"]').count(), 1, 'contact activates wiring in select mode');
  await clickAt(490, 240);
  console.log('after first wire', await page.locator('#schematic-world path[stroke="transparent"]').count());
  await page.getByRole('button', { name: 'Резистор' }).first().click();
  await clickAt(720, 380);
  await clickAt(550, 240);
  console.log('after source', await page.locator('#schematic-world path[stroke-dasharray="4 3"]').count(), await page.locator('#schematic-world path[stroke="transparent"]').count());
  await page.screenshot({ path: '.work/browser-source.png' });
  await clickAt(630, 320);
  console.log('after waypoint', await page.locator('#schematic-world path[stroke-dasharray="4 3"]').count(), await page.locator('#schematic-world path[stroke="transparent"]').count());
  await page.screenshot({ path: '.work/browser-waypoint.png' });
  await clickAt(690, 380);
  const wirePaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  console.log(JSON.stringify({ stage: 'wired', wirePaths, errors }, null, 2));
  assert.equal(wirePaths.length, 2);
  assert.equal(wirePaths[1], 'M 550 240 L 690 380');
  await page.getByRole('button', { name: 'Резистор' }).first().click();
  await clickAt(900, 300);
  await clickAt(870, 300);
  await clickAt(620, 310);
  const branchedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  console.log(JSON.stringify({ stage: 'branched', branchedPaths, elementCount: await page.locator('#schematic-world > g[transform^="translate"]').count(), errors }, null, 2));
  assert.equal(branchedPaths.length, 4, 'branch creates two visible split wires and one incoming wire');
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 5, 'branch creates an explicit junction');
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByRole('button', { name: 'Сохранить' }).click(),
  ]);
  const scm = await fs.readFile(await download.path(), 'utf8');
  assert.match(scm, /Manual: true/);
  assert.match(scm, /Waypoints:/);
  const topology = await page.evaluate(async content => {
    const { parseYamlScm } = await import('/src/utils/yamlScm.ts');
    const { buildCircuitGraph } = await import('/src/math/circuitSolver.ts');
    const parsed = parseYamlScm(content);
    const graph = buildCircuitGraph(parsed.elements, parsed.wires);
    return { elements: parsed.elements.map(element => [element.id, element.name, element.type]), wires: parsed.wires.length, nodes: [...graph.pinToNode] };
  }, scm);
  console.log(JSON.stringify({ stage: 'scm', topology, manualCount: (scm.match(/Manual: true/g) || []).length }, null, 2));
  assert.equal(topology.wires, 4);
  assert.equal(topology.elements.length, 5);
  const ids = Object.fromEntries(topology.elements.map(([id, name]) => [name, id]));
  const nodes = new Map(topology.nodes);
  assert.equal(nodes.get(ids.R2 + '_2'), nodes.get(ids.R3 + '_1'));
  assert.equal(nodes.get(ids.R3 + '_1'), nodes.get(ids.R4 + '_1'));
  assert.notEqual(nodes.get(ids.R1 + '_2'), nodes.get(ids.R3 + '_1'));
  const viewportBeforeUndo = await page.locator('#schematic-world').getAttribute('transform');
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#schematic-world').getAttribute('transform'), viewportBeforeUndo, 'undo preserves zoom and pan');
  assert.equal(await page.locator('#schematic-world path[stroke="transparent"]').count(), 2, 'undo removes the branch as one action');
  await page.keyboard.press('Control+y');
  assert.equal(await page.locator('#schematic-world').getAttribute('transform'), viewportBeforeUndo, 'redo preserves zoom and pan');
  assert.equal(await page.locator('#schematic-world path[stroke="transparent"]').count(), 4, 'redo restores the branch');
  await page.locator('input[type="file"]').setInputFiles({ name: 'roundtrip.scm', mimeType: 'text/plain', buffer: Buffer.from(scm) });
  await page.getByText('roundtrip', { exact: true }).waitFor();
  const reloadedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  assert.deepEqual(reloadedPaths, branchedPaths, 'SCM reload preserves visible route topology');
  const screenPoint = (x, y) => page.evaluate(([x, y]) => {
    const world = document.querySelector('#schematic-world');
    const svg = world.ownerSVGElement;
    const p = svg.createSVGPoint();
    p.x = x; p.y = y;
    const result = p.matrixTransform(world.getScreenCTM());
    return { x: result.x, y: result.y };
  }, [x, y]);
  const segmentStart = await screenPoint(740, 300);
  const segmentEnd = await screenPoint(740, 340);
  await page.mouse.move(segmentStart.x, segmentStart.y);
  await page.mouse.down();
  await page.mouse.move(segmentEnd.x, segmentEnd.y, { steps: 5 });
  await page.mouse.up();
  const editedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  console.log(JSON.stringify({ stage: 'segment-edit', editedPaths }, null, 2));
  assert.notDeepEqual(editedPaths, reloadedPaths, 'segment edit changes the visible route');
  assert.ok(editedPaths[3].startsWith('M 870 300') && editedPaths[3].endsWith('620 310'), 'segment edit retains electrical endpoints');
  await page.keyboard.press('Control+z');
  assert.deepEqual(await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d'))), reloadedPaths);
  await page.keyboard.press('Control+y');
  assert.deepEqual(await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d'))), editedPaths);
  const r2Start = await screenPoint(520, 240);
  const r2End = await screenPoint(560, 200);
  await page.mouse.move(r2Start.x, r2Start.y);
  await page.mouse.down();
  await page.mouse.move(r2End.x, r2End.y, { steps: 5 });
  await page.mouse.up();
  const movedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  assert.ok(movedPaths[0].endsWith('530 200'), 'connected wire follows moved R2 pin');
  const r2Moved = await screenPoint(560, 200);
  await page.mouse.click(r2Moved.x, r2Moved.y);
  await page.keyboard.press('Shift+r');
  const rotatedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  assert.notDeepEqual(rotatedPaths, movedPaths, '45-degree rotation updates attached route');
  console.log(JSON.stringify({ stage: 'moved-rotated', movedPaths, rotatedPaths, errors }, null, 2));
  await page.keyboard.press('Delete');
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 4, 'delete removes the selected connected component');
  assert.equal(await page.locator('#schematic-world path[stroke="transparent"]').count(), 2, 'delete also removes its two attached wires');
  await page.keyboard.press('Control+z');
  assert.equal(await page.locator('#schematic-world > g[transform^="translate"]').count(), 5, 'undo restores the connected component');
  assert.equal(await page.locator('#schematic-world path[stroke="transparent"]').count(), 4, 'undo restores both attached wires');
  await page.screenshot({ path: '.work/browser-wired.png' });
  const fixtures = await page.evaluate(async () => {
    const { exportToYamlScm } = await import('/src/utils/yamlScm.ts');
    const { SAMPLE_CIRCUITS } = await import('/src/data/sampleCircuits.ts');
    const el = (id, type, name, x, y) => ({ id, type, name, x, y, rotation: 0, value: type === 'JUNCTION' ? 0 : 1000, valueStr: type === 'JUNCTION' ? '' : '1к', unit: type === 'JUNCTION' ? '' : 'Ом' });
    const elements = [el('A', 'R', 'A', 100, 100), el('B', 'R', 'B', 500, 100), el('C', 'JUNCTION', 'C', 300, 20), el('D', 'JUNCTION', 'D', 300, 180)];
    const w = (id, fromCompId, fromPinId, toCompId, toPinId) => ({ id, fromCompId, fromPinId, toCompId, toPinId });
    const crossing = exportToYamlScm(elements, [w('h', 'A', '2', 'B', '1'), w('v', 'C', '1', 'D', '1')], SAMPLE_CIRCUITS[0].transient);
    const joined = exportToYamlScm([...elements, el('J', 'JUNCTION', 'J', 300, 100)], [w('h1', 'A', '2', 'J', '1'), w('h2', 'J', '1', 'B', '1'), w('v1', 'C', '1', 'J', '1'), w('v2', 'J', '1', 'D', '1')], SAMPLE_CIRCUITS[0].transient);
    const parallelElements = [el('PL', 'JUNCTION', 'PL', 100, 200), el('PR', 'JUNCTION', 'PR', 500, 200), el('P1', 'R', 'P1', 300, 100), el('P2', 'R', 'P2', 300, 300)];
    const parallel = exportToYamlScm(parallelElements, [w('p1a', 'PL', '1', 'P1', '1'), w('p1b', 'P1', '2', 'PR', '1'), w('p2a', 'PL', '1', 'P2', '1'), w('p2b', 'P2', '2', 'PR', '1')], SAMPLE_CIRCUITS[0].transient);
    return { crossing, joined, parallel };
  });
  page.on('dialog', dialog => dialog.accept());
  const graphFor = async content => page.evaluate(async scmText => {
    const { parseYamlScm } = await import('/src/utils/yamlScm.ts');
    const { buildCircuitGraph } = await import('/src/math/circuitSolver.ts');
    const parsed = parseYamlScm(scmText);
    const graph = buildCircuitGraph(parsed.elements, parsed.wires);
    const ids = Object.fromEntries(parsed.elements.map(element => [element.name, element.id]));
    return { a: graph.pinToNode.get(ids.A + '_2'), c: graph.pinToNode.get(ids.C + '_1') };
  }, content);
  await page.locator('input[type="file"]').setInputFiles({ name: 'crossing.scm', mimeType: 'text/plain', buffer: Buffer.from(fixtures.crossing) });
  await page.getByText('crossing', { exact: true }).waitFor();
  const crossingPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  assert.equal(crossingPaths.length, 2);
  assert.notEqual((await graphFor(fixtures.crossing)).a, (await graphFor(fixtures.crossing)).c, 'visible crossing without junction is electrically distinct');
  await page.screenshot({ path: '.work/browser-crossing.png' });
  await page.locator('input[type="file"]').setInputFiles({ name: 'joined.scm', mimeType: 'text/plain', buffer: Buffer.from(fixtures.joined) });
  await page.getByText('joined', { exact: true }).waitFor();
  const joinedPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  assert.equal(joinedPaths.length, 4);
  assert.equal((await graphFor(fixtures.joined)).a, (await graphFor(fixtures.joined)).c, 'explicit crossing junction unifies both branches');
  await page.screenshot({ path: '.work/browser-crossing-junction.png' });
  console.log(JSON.stringify({ stage: 'crossings', crossingPaths, joinedPaths, errors }, null, 2));
  await page.locator('input[type="file"]').setInputFiles({ name: 'parallel.scm', mimeType: 'text/plain', buffer: Buffer.from(fixtures.parallel) });
  await page.getByText('parallel', { exact: true }).waitFor();
  const parallelPaths = await page.locator('#schematic-world path[stroke="transparent"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  const parallelGraph = await page.evaluate(async content => {
    const { parseYamlScm } = await import('/src/utils/yamlScm.ts');
    const { buildCircuitGraph } = await import('/src/math/circuitSolver.ts');
    const parsed = parseYamlScm(content);
    const node = buildCircuitGraph(parsed.elements, parsed.wires).pinToNode;
    const ids = Object.fromEntries(parsed.elements.map(element => [element.name, element.id]));
    return [node.get(ids.P1 + '_1'), node.get(ids.P2 + '_1'), node.get(ids.P1 + '_2'), node.get(ids.P2 + '_2')];
  }, fixtures.parallel);
  assert.equal(parallelPaths.length, 4);
  assert.equal(parallelGraph[0], parallelGraph[1], 'both branch inputs share the left junction');
  assert.equal(parallelGraph[2], parallelGraph[3], 'both branch outputs share the right junction');
  assert.notEqual(parallelGraph[0], parallelGraph[2], 'parallel branch sides stay distinct');
  await page.screenshot({ path: '.work/browser-parallel.png' });
  console.log(JSON.stringify({ stage: 'parallel', parallelPaths, parallelGraph, errors }, null, 2));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
